##  Plugin Information  ##
name: PublicEnemy
version: 1.0
main: com.happytarn.PublicEnemy.PublicEnemy
description:
##  Original Author     ##
author: happytarn
commands:
    publicenemy:
      usage: /pe help - to see the help
      aliases: [pe]
      description: To see the PublicEnemy help.
permissions:
    hapitanCmd.enemy.easy:
        default: op
        description: Can se Reload.
    hapitanCmd.enemy.normal:
        default: op
        description: Can se Reload.
    hapitanCmd.enemy.hard:
        default: op
        description: Can se Reload.
    hapitanCmd.enemy.god:
        default: op
        description: Can se Reload.
